# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buddy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('expertise', models.CharField(blank=True, choices=[('CERTIFIED', 'Certified'), ('TRAINEE', 'Trainee')], max_length=10, null=True)),
                ('type', models.CharField(blank=True, choices=[('LEAD', 'Lead'), ('SUPPORT', 'Support')], max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=100)),
                ('sports4You_id', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='buddy_pic')),
            ],
        ),
        migrations.CreateModel(
            name='Buddy_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField(default=2.5)),
                ('buddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Buddy')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drill_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='Drill Images')),
                ('set_number', models.IntegerField(blank=True, null=True)),
                ('image_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('face_picture', models.ImageField(blank=True, null=True, upload_to='location')),
                ('address', models.TextField(blank=True, null=True)),
                ('centre_head', models.CharField(blank=True, max_length=100, null=True)),
                ('centre_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(max_length=120)),
                ('City', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.City')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('session_duration', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=100)),
                ('fitness_score', models.IntegerField(blank=True, null=True)),
                ('skill_score', models.IntegerField(blank=True, null=True)),
                ('tactics_score', models.IntegerField(blank=True, null=True)),
                ('others_score', models.IntegerField(blank=True, null=True)),
                ('MTG_fina_score', models.IntegerField(blank=True, null=True)),
                ('injuries', models.TextField(blank=True, null=True)),
                ('current_injury_status', models.TextField(blank=True, null=True)),
                ('rehabilitation_date', models.DateField(blank=True, null=True)),
                ('recommended_exercises', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='player_pic')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.City')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Package')),
            ],
        ),
        migrations.CreateModel(
            name='Player_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField(default=2.5)),
                ('buddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Player')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Buddy')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_physic_attend', models.BooleanField(default=True)),
                ('max_player_count', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('drill_start_time', models.DateTimeField(blank=True, null=True)),
                ('drill_end_time', models.DateTimeField(blank=True, null=True)),
                ('match_start_time', models.DateTimeField(blank=True, null=True)),
                ('match_end_time', models.DateTimeField(blank=True, null=True)),
                ('warmup_start_time', models.DateTimeField(blank=True, null=True)),
                ('warmup_end_time', models.DateTimeField(blank=True, null=True)),
                ('buddy', models.ManyToManyField(blank=True, null=True, to='api.Buddy')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Location')),
                ('players', models.ManyToManyField(blank=True, null=True, related_name='player', to='api.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Skill_tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_intelligence', models.FloatField(blank=True, default=2.5, null=True)),
                ('recieving', models.FloatField(blank=True, default=2.5, null=True)),
                ('passing', models.FloatField(blank=True, default=2.5, null=True)),
                ('dribbling', models.FloatField(blank=True, default=2.5, null=True)),
                ('attacking', models.FloatField(blank=True, default=2.5, null=True)),
                ('defending', models.FloatField(blank=True, default=2.5, null=True)),
                ('endurance', models.CharField(blank=True, max_length=100, null=True)),
                ('injuriy_details', models.FloatField(blank=True, null=True)),
                ('is_attended', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Player')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Session')),
                ('buddy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Buddy')),
                ('players', models.ManyToManyField(to='api.Player')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='sports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Sports'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Player'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Buddy'),
        ),
        migrations.AddField(
            model_name='location',
            name='sports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Sports'),
        ),
        migrations.AddField(
            model_name='drill_images',
            name='sports',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sports'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.State'),
        ),
        migrations.AddField(
            model_name='buddy_rating',
            name='rated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Player'),
        ),
    ]
